# Generated by Django 6.0.1 on 2026-01-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroceriesList',
            new_name='Grocery',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
